name: belajar_dart_library
description: This is library from ArtCode
version: 1.5.0
homepage: http://sutracipondok.my.id
repository: https://github.com/rhehan7/belajar_dart_library

environment:
  sdk: '>=2.19.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
